language: minimal
sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse --short HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project spring-ember-310020
    - gcloud config set compute/zone us-central1-c
    - gcloud container clusters get-credentials multi-cluster
    - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - docker build -t suguiura/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true suguiura/react-test npm test

deploy:
    provider: script
    scripts: bash ./deploy.sh
    on:
        branch: master
